project:
  type: website
  output-dir: docs

website:
  title: "Supervisión CAWI"
  site-url: "https://ftorov.github.io/dashboard_SV"
  favicon: "assets/images/logo_ine.png"
  
  navbar:
    background: primary                        
    logo: "assets/images/LOGO INE.png"   
    
  sidebar:
    pinned: true                             
    style: "floating"                          
    collapse-level: 1                          
    search: true                               
    contents:
      - href: index.qmd
        text: Inicio
        icon: house
        
      - section: "Encuestas"
        icon: clipboard-data
        contents:
         - text: "Encuesta Nacional de Innovación"
           icon: bi bi-lightbulb
           href: ENI.qmd
         - text: "Encuesta Nacional Industrial Anual"
           icon: bi bi-boxes
           href: ENIA.qmd
         - text: "Encuesta Longitudinal de Empresas"
           icon: bi bi-building
           href: ELE.qmd
         - text: "Encuesta de Oferta Cultural"
           icon: bi bi-palette
           href: EOC.qmd
      - section: "Tabulados"
        icon: file-earmark-bar-graph
        contents:
          - text: "Descargas"
            icon: download
            href: descargas.qmd
  
      - section: "Documentación"
        icon: journal-text
        contents:
          - text: "Metodología"
            icon: diagram-3
            href: metodologia.qmd
    
  page-footer:
    left: Subdepartamento de Supervisión y Verificación de Estadísticas Económicas y Precios

format:
  html:
    theme:
      light: cosmo                 # Tema claro
      dark: darkly                 # Tema oscuro
      
    back-to-top: true
    page-navigation: true          # Navegación entre páginas
    anchor-sections: true          # Anclas en los títulos
    smooth-scroll: true            # Desplazamiento suave
    link-external-newwindow: true  # Enlaces externos abren nueva pestaña
    link-external-icon: true       # Muestra icono en enlaces externos
    code-fold: false               # No pliega bloques de codigo
    code-copy: false               # No muestra botón de copiar
    code-tools: false              # Sin herramientas de código
    code-overflow: wrap            # Ajuste de líneas largas
    number-sections: false         # No numera secciones
    title-block-banner: false       # Banner en el título
    sanitize: false                # Permite HTML sin sanitizar
    css: 
    - styles.css
    - https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css
    toc: false
    grid:
     sidebar-width: "240px"       # Ancho de la barra lateral
     body-width: "1400px"         # Ancho del contenido central
     margin-width: "140px"        # Márgenes laterales

editor: visual

execute:
  echo: false          # Oculta el código en los documentos
  warning: false       # Oculta advertencias
  message: false       # Oculta mensajes
  error: false         # Oculta errores
  cache: false         # No usa caché
  freeze: auto         # Recalcula solo si el archivo cambió
  encoding: "UTF-8"    # Codificación de texto
