project:
  type: website
  output-dir: docs

website:
  title: "dashboard_SV"
  site-url: "https://ftorov.github.io/dashboard_SV"
  favicon: "assets/images/logo_ine.png"
  
  sidebar:
    pinned: true                             
    style: "floating"                          
    collapse-level: 1                          
    search: true                               
    contents:
      - href: index.qmd
        text: Home
        icon: house
      - section: "Encuestas"
        icon: clipboard-data
        contents:
         - text: "Encuesta Nacional de Innovaci√≥n"
           icon: lightbulb
           href: ENI.qmd
         - text: "Encuesta Nacional Industrial Anual"
           icon: boxes
           href: ENIA.qmd
         - text: "Encuesta Longitudinal de Empresas"
           icon: layers
           href: ELE.qmd
         - text: "Encuesta de Oferta Cultural"
           icon: palette
           href: EOC.qmd
      - text: "Descargas"
        icon: download
        href: descargas.qmd

format:
  html:
    theme: cosmo

